import React, { useState } from 'react';
import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  IconButton,
  Tooltip,
  Box,
  Typography,
  Chip,
  Menu,
  MenuItem,
  CircularProgress,
  useTheme,
} from '@mui/material';
import {
  Download as DownloadIcon,
  Delete as DeleteIcon,
  MoreVert as MoreVertIcon,
  Description as DescriptionIcon,
} from '@mui/icons-material';
import { StoredReportDto } from '../types/report.types';
import { formatDistanceToNow } from 'date-fns';

interface StoredReportsListProps {
  reports: StoredReportDto[];
  loading: boolean;
  totalCount: number;
  page: number;
  rowsPerPage: number;
  onPageChange: (page: number) => void;
  onRowsPerPageChange: (rowsPerPage: number) => void;
  onDownload: (id: string, fileName: string) => void;
  onDelete: (id: string) => void;
}

const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
};

export const StoredReportsList: React.FC<StoredReportsListProps> = ({
  reports = [],
  loading,
  totalCount = 0,
  page = 0,
  rowsPerPage = 25,
  onPageChange,
  onRowsPerPageChange,
  onDownload,
  onDelete,
}) => {
  const theme = useTheme();
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
  const [selectedReportId, setSelectedReportId] = useState<string | null>(null);

  // Safety check: ensure reports is always an array
  const safeReports = reports || [];

  const handleMenuOpen = (event: React.MouseEvent<HTMLElement>, reportId: string) => {
    setAnchorEl(event.currentTarget);
    setSelectedReportId(reportId);
  };

  const handleMenuClose = () => {
    setAnchorEl(null);
    setSelectedReportId(null);
  };

  const handleDownload = () => {
    if (selectedReportId) {
      const report = safeReports.find((r) => r.id === selectedReportId);
      if (report) {
        onDownload(report.id, report.fileName);
      }
    }
    handleMenuClose();
  };

  const handleDelete = () => {
    if (selectedReportId) {
      onDelete(selectedReportId);
    }
    handleMenuClose();
  };

  return (
    <Paper elevation={0} sx={{ border: (theme) => `1px solid ${theme.palette.divider}` }}>
      <TableContainer>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>File Name</TableCell>
              <TableCell>Type</TableCell>
              <TableCell>Entity Type</TableCell>
              <TableCell>Generated By</TableCell>
              <TableCell>Generated At</TableCell>
              <TableCell>Size</TableCell>
              <TableCell align="right">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell colSpan={7} align="center" sx={{ py: 4 }}>
                  <CircularProgress size={24} />
                </TableCell>
              </TableRow>
            ) : safeReports.length === 0 ? (
              <TableRow>
                <TableCell colSpan={7} align="center" sx={{ py: 4 }}>
                  <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 1 }}>
                    <DescriptionIcon sx={{ fontSize: 48, color: 'text.secondary' }} />
                    <Typography variant="body2" color="text.secondary">
                      No stored reports found
                    </Typography>
                  </Box>
                </TableCell>
              </TableRow>
            ) : (
              safeReports.map((report) => (
                <TableRow key={report.id} hover>
                  <TableCell>
                    <Typography variant="body2" sx={{ fontWeight: 500 }}>
                      {report.fileName}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={report.reportType}
                      size="small"
                      color="primary"
                      variant="outlined"
                    />
                  </TableCell>
                  <TableCell>
                    {report.entityType || report.metadata?.entityType ? (
                      <Chip
                        label={report.entityType || report.metadata?.entityType}
                        size="small"
                        variant="outlined"
                      />
                    ) : (
                      <Typography variant="body2" color="text.secondary">
                        -
                      </Typography>
                    )}
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2">{report.generatedBy}</Typography>
                  </TableCell>
                  <TableCell>
                    {report.generatedAt || report.metadata?.generatedAt ? (
                      <>
                        <Typography variant="body2">
                          {formatDistanceToNow(
                            new Date(report.generatedAt || report.metadata?.generatedAt),
                            { addSuffix: true }
                          )}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          {new Date(report.generatedAt || report.metadata?.generatedAt).toLocaleString()}
                        </Typography>
                      </>
                    ) : (
                      <Typography variant="body2" color="text.secondary">
                        {new Date(report.createdAt).toLocaleString()}
                      </Typography>
                    )}
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2">
                      {formatFileSize(
                        typeof report.fileSize === 'string' ? parseInt(report.fileSize, 10) : report.fileSize
                      )}
                    </Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Tooltip title="Download">
                      <IconButton
                        size="small"
                        onClick={() => onDownload(report.id, report.fileName)}
                        sx={{ mr: 1 }}
                      >
                        <DownloadIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>
                    <Tooltip title="More options">
                      <IconButton
                        size="small"
                        onClick={(e) => handleMenuOpen(e, report.id)}
                      >
                        <MoreVertIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </TableContainer>

      <TablePagination
        component="div"
        count={totalCount}
        page={page}
        onPageChange={(_, newPage) => onPageChange(newPage)}
        rowsPerPage={rowsPerPage}
        onRowsPerPageChange={(e) => {
          const newRowsPerPage = parseInt(e.target.value, 10);
          onRowsPerPageChange(newRowsPerPage);
        }}
        rowsPerPageOptions={[10, 25, 50, 100]}
        labelRowsPerPage="Rows per page:"
        labelDisplayedRows={({ from, to, count }) => {
          if (loading) {
            return 'Loading...';
          }
          return `${from}–${to} of ${count !== -1 ? count : `more than ${to}`}`;
        }}
        disabled={loading}
        sx={{
          borderTop: `1px solid ${theme.palette.divider}`,
          '& .MuiTablePagination-select': {
            pr: 1,
          },
          '& .MuiTablePagination-displayedRows': {
            fontSize: '0.875rem',
            color: theme.palette.text.secondary,
          },
          '&.Mui-disabled': {
            opacity: 0.6,
          },
        }}
      />

      <Menu
        anchorEl={anchorEl}
        open={Boolean(anchorEl)}
        onClose={handleMenuClose}
      >
        <MenuItem onClick={handleDownload}>
          <DownloadIcon fontSize="small" sx={{ mr: 1 }} />
          Download
        </MenuItem>
        <MenuItem onClick={handleDelete} sx={{ color: 'error.main' }}>
          <DeleteIcon fontSize="small" sx={{ mr: 1 }} />
          Delete
        </MenuItem>
      </Menu>
    </Paper>
  );
};

