export const mockData = {
    vehicles: [
        {
            id: 1,
            make: 'Hyundai',
            model: 'Santa Fe',
            year: 2020,
            license_plate: 'AB818AY',
            chassis: 'KMHS381CDLU306093',
            status: 'unavailable',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2023-07-22',
            kasko_expiry: '2024-06-13',
            passenger_insurance: 'None'
        },
        {
            id: 2,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB423EC',
            chassis: 'KMHK381GFMU137966',
            status: 'leased',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-07-31',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 3,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB284EC',
            chassis: 'KMHK381GFMU137962',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-07-31',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 4,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB318EC',
            chassis: 'KMHK381GFMU137971',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-07-31',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 5,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB332EC',
            chassis: 'KMHK381GFMU137224',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-07-31',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 6,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB343EC',
            chassis: 'KMHK381GFMU137267',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-07-31',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 7,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB292EC',
            chassis: 'KMHK381GFMU139516',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-08-01',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 8,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB211EC',
            chassis: 'KMHK381GFMU139539',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-07-31',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 9,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB349EC',
            chassis: 'KMHK381GFMU139593',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-08-04',
            kasko_expiry: '2025-07-31',
            passenger_insurance: 'None'
        },
        {
            id: 10,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB403EC',
            chassis: 'KMHK381GFMU139598',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-07-31',
            kasko_expiry: '2025-07-31',
            passenger_insurance: '2025-08-01'
        },
        {
            id: 11,
            make: 'Bmw',
            model: 'Team',
            year: 2021,
            license_plate: 'BH547',
            chassis: 'WB10M1104M6E78692',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'TEAM SHPK',
            insurance: 'ANSIG',
            tpl_expiry: '2025-08-06',
            kasko_expiry: '2025-08-06',
            passenger_insurance: 'None'
        },
        {
            id: 12,
            make: 'Hyundai',
            model: 'I20',
            year: 2020,
            license_plate: 'AB018AZ',
            chassis: 'NLHB251CBLZ627453',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE RENTALS SHPK  ',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2023-08-15',
            kasko_expiry: '2024-06-29',
            passenger_insurance: 'None'
        },
        {
            id: 13,
            make: 'Ford',
            model: 'Transit',
            year: 2021,
            license_plate: 'AB294EK',
            chassis: 'WF0EXXTTREMJ74943',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ARMAND SPAHJA PF',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-09-05',
            kasko_expiry: '2025-09-05',
            passenger_insurance: 'None'
        },
        {
            id: 14,
            make: 'Toyota',
            model: 'Rav4',
            year: 2020,
            license_plate: 'AB912BG',
            chassis: 'JTMDW3FV60J052280',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TEAM SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: 'nan',
            kasko_expiry: '2025-08-22',
            passenger_insurance: 'None'
        },
        {
            id: 15,
            make: 'Ford',
            model: 'Tourneo',
            year: 2016,
            license_plate: 'AA713OS',
            chassis: 'WF0UXXWPGUGD15285',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE RENTALS SHPK  ',
            color: 'BLU',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2023-10-02',
            kasko_expiry: '2024-01-17',
            passenger_insurance: 'None'
        },
        {
            id: 16,
            make: 'Hyundai ',
            model: 'I20',
            year: 2021,
            license_plate: 'AB461ET',
            chassis: 'NLHBM51JBNZ102138',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-09',
            kasko_expiry: '2025-10-09',
            passenger_insurance: 'None'
        },
        {
            id: 17,
            make: 'Hyundai ',
            model: 'Tucson',
            year: 2021,
            license_plate: 'AB630ET',
            chassis: 'TMAJB811DMJ049222',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-09',
            kasko_expiry: '2025-10-09',
            passenger_insurance: 'None'
        },
        {
            id: 18,
            make: 'Scoda',
            model: 'Octavia',
            year: 2021,
            license_plate: 'AB620ET',
            chassis: 'TMBAG6NX1NY022347',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-14',
            kasko_expiry: '2025-10-14',
            passenger_insurance: 'None'
        },
        {
            id: 19,
            make: 'Land Rover',
            model: 'Discovery',
            year: 2017,
            license_plate: 'AB500LF',
            chassis: 'SALRHBBK7HA021842',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'EDLIR FUSHA',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-18',
            kasko_expiry: '2025-10-18',
            passenger_insurance: 'None'
        },
        {
            id: 20,
            make: 'Hyundai',
            model: 'Ioniq',
            year: 2021,
            license_plate: 'AB532FA',
            chassis: 'KMHC751JFMU077528',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-11-14',
            kasko_expiry: '2025-11-14',
            passenger_insurance: '2025-12-11'
        },
        {
            id: 21,
            make: 'Hyundai',
            model: 'Ioniq',
            year: 2021,
            license_plate: 'AB551FA',
            chassis: 'KMHC751JFMU077526',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-11-13',
            kasko_expiry: '2025-11-13',
            passenger_insurance: '2025-12-11'
        },
        {
            id: 22,
            make: 'Hyundai',
            model: 'Ioniq',
            year: 2020,
            license_plate: 'AB647FD',
            chassis: 'KMHC851JFLU073836',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'FERMA 100 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: 'nan',
            kasko_expiry: '2025-12-05',
            passenger_insurance: 'None'
        },
        {
            id: 23,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB082FH',
            chassis: 'KMHK381GFNU144721',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-12',
            passenger_insurance: '2025-12-12'
        },
        {
            id: 24,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB036FH',
            chassis: 'KMHK381GFNU144714',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-12',
            passenger_insurance: '2025-12-12'
        },
        {
            id: 25,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB034FH',
            chassis: 'KMHK381GFNU144791',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-12',
            passenger_insurance: '2025-12-12'
        },
        {
            id: 26,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB041FH',
            chassis: 'KMHK381GFNU144806',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'S.S 2018 SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-12',
            passenger_insurance: '2025-12-12'
        },
        {
            id: 27,
            make: 'Ford',
            model: 'Puma ',
            year: 2021,
            license_plate: 'AB849FI',
            chassis: 'WF02XXERK2MU8005',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BLU',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-13',
            kasko_expiry: '2025-12-14',
            passenger_insurance: 'None'
        },
        {
            id: 28,
            make: 'Mercedes Benz',
            model: 'Gle 400',
            year: 2021,
            license_plate: 'AB440FM',
            chassis: 'W1N1671231A564836',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-09',
            kasko_expiry: '2026-01-09',
            passenger_insurance: 'None'
        },
        {
            id: 29,
            make: 'Skoda',
            model: 'Octavia',
            year: 2021,
            license_plate: 'AB951FO',
            chassis: 'TMBAG6NX9NY018532',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2026-01-28',
            kasko_expiry: '2026-01-28',
            passenger_insurance: 'None'
        },
        {
            id: 30,
            make: 'Ford',
            model: 'Transit',
            year: 2015,
            license_plate: 'AB479EC',
            chassis: 'WF0XXXTTGXFT43639',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'LEO-FM COMPANY SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-03-05',
            kasko_expiry: '2025-08-01',
            passenger_insurance: 'None'
        },
        {
            id: 31,
            make: 'Ford',
            model: 'Transit',
            year: 2021,
            license_plate: 'AB731DE',
            chassis: 'WF0EXXTTREMJ68356',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2024-04-27',
            kasko_expiry: '2024-05-02',
            passenger_insurance: 'None'
        },
        {
            id: 32,
            make: 'Alfa Romeo',
            model: 'Giulia',
            year: 2021,
            license_plate: 'AB414DE',
            chassis: 'ZAREAEEV4M7646701',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2024-04-26',
            kasko_expiry: '2024-04-26',
            passenger_insurance: 'None'
        },
        {
            id: 33,
            make: 'Jeep',
            model: 'Compass',
            year: 2018,
            license_plate: 'AB435BM',
            chassis: '3C4NJDCH1KT591456',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2023-10-18',
            kasko_expiry: '2023-10-18',
            passenger_insurance: 'None'
        },
        {
            id: 34,
            make: 'Fiat',
            model: 'Doblo',
            year: 2021,
            license_plate: 'AB595DE',
            chassis: 'ZFA26300006U23617',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2024-04-26',
            kasko_expiry: '2024-04-26',
            passenger_insurance: 'None'
        },
        {
            id: 35,
            make: 'Fiat',
            model: 'Doblo',
            year: 2020,
            license_plate: 'AB596CP',
            chassis: 'ZFA26300006T21781',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2025-02-20',
            kasko_expiry: '2025-02-20',
            passenger_insurance: 'None'
        },
        {
            id: 36,
            make: 'Alfa Romeo',
            model: 'Stelvio',
            year: 2018,
            license_plate: 'AA648VE',
            chassis: 'ZARPAHBX1K7C29763',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2024-11-02',
            kasko_expiry: '2024-11-02',
            passenger_insurance: 'None'
        },
        {
            id: 37,
            make: 'Alfa Romeo',
            model: 'Stelvio',
            year: 2018,
            license_plate: 'AA279VL',
            chassis: 'ZARPAHBX6K7C29967',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BLU',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2024-11-09',
            kasko_expiry: '2024-11-02',
            passenger_insurance: 'None'
        },
        {
            id: 38,
            make: 'Honda',
            model: 'Sc79',
            year: 2021,
            license_plate: 'BI 616',
            chassis: 'JH2SC79B2MK301335',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-25',
            kasko_expiry: '2025-10-25',
            passenger_insurance: 'None'
        },
        {
            id: 39,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB204GE',
            chassis: 'KMHKM81AFNU075563',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 40,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB211GE',
            chassis: 'KMHKM81AFNU075530',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 41,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB215GE',
            chassis: 'KMHKM81AFNU075552',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 42,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB227GE',
            chassis: 'KMHKM81AFNU075562',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 43,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB228GE',
            chassis: 'KMHKM81AFNU075534',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 44,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB229GE',
            chassis: 'KMHKM81AFNU075541',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 45,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB233GE',
            chassis: 'KMHKM81AFNU075524',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 46,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB238GE',
            chassis: 'KMHKM81AFNU075522',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-31',
            kasko_expiry: '2026-03-31',
            passenger_insurance: '2025-10-10'
        },
        {
            id: 47,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB950FI',
            chassis: 'KMHK381GFNU144784',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-12-19',
            kasko_expiry: '2025-12-19',
            passenger_insurance: '2025-12-19'
        },
        {
            id: 48,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB927FI',
            chassis: 'KMHK381GFNU144730',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-12-19',
            kasko_expiry: '2025-12-19',
            passenger_insurance: '2025-12-19'
        },
        {
            id: 49,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AB953FI',
            chassis: 'KMHK381GFNU144799',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ECM INTERNATIONAL SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-12-19',
            kasko_expiry: '2025-12-19',
            passenger_insurance: '2025-12-19'
        },
        {
            id: 50,
            make: 'Audi',
            model: 'A8',
            year: 2018,
            license_plate: 'AB429FV',
            chassis: 'WAUZZZF87JN005311',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'HANXHARI GROUP SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-02-13',
            kasko_expiry: '2026-02-13',
            passenger_insurance: 'None'
        },
        {
            id: 51,
            make: 'Mazda',
            model: 'Cx-5',
            year: 2018,
            license_plate: 'AA073VB',
            chassis: 'JMZKFGW1A00754733',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2023-10-20',
            kasko_expiry: '2023-08-02',
            passenger_insurance: 'None'
        },
        {
            id: 52,
            make: 'Jeep',
            model: 'Renegade',
            year: 2017,
            license_plate: 'AA229TI',
            chassis: '1C4BU0000HPG43565',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2025-02-21',
            kasko_expiry: '2023-10-26',
            passenger_insurance: 'None'
        },
        {
            id: 53,
            make: 'Jeep',
            model: 'Renegade',
            year: 2017,
            license_plate: 'AA230TI',
            chassis: '1C4BU0000HPG38380',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'AUTO MASTER SHA',
            insurance: 'SIGMA',
            tpl_expiry: '2025-02-21',
            kasko_expiry: '2023-10-26',
            passenger_insurance: 'None'
        },
        {
            id: 54,
            make: 'Audi',
            model: 'Q7',
            year: 2016,
            license_plate: 'AB354FX',
            chassis: 'WAUZZZ4M2GD064085',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'BLU',
            client: 'DENIS PATUZI PF',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-02-15',
            kasko_expiry: '2025-02-16',
            passenger_insurance: 'None'
        },
        {
            id: 55,
            make: 'Audi',
            model: 'A6',
            year: 2020,
            license_plate: 'AB485FL',
            chassis: 'WAUZZZF2XLN055733',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'DENIS PATUZI PF',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-02-15',
            kasko_expiry: '2026-02-18',
            passenger_insurance: 'None'
        },
        {
            id: 56,
            make: 'Maxus',
            model: 'Maxus E-Deliver 3',
            year: 2021,
            license_plate: 'AB657GH',
            chassis: 'LSH14C4CXMA089686',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'DENIS PATUZI PF',
            insurance: 'INTERSIG',
            tpl_expiry: '2025-04-11',
            kasko_expiry: '2025-04-11',
            passenger_insurance: 'None'
        },
        {
            id: 57,
            make: 'Land Rover ',
            model: 'Range Rover Evoque',
            year: 2019,
            license_plate: 'AB074GC',
            chassis: 'SALZA2BN9LH033439',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI',
            client: 'NIKI ZONJA PF',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-07',
            kasko_expiry: '2026-03-07',
            passenger_insurance: 'None'
        },
        {
            id: 58,
            make: 'Hyundai',
            model: 'Ioniq',
            year: 2022,
            license_plate: 'AB152GE',
            chassis: 'KMHC751JFMU082564',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'FLORENC REXHOLLARI PF',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-28',
            kasko_expiry: '2026-03-28',
            passenger_insurance: '2026-04-09'
        },
        {
            id: 59,
            make: 'Hyundai',
            model: 'Venue',
            year: 2022,
            license_plate: 'AB229GF',
            chassis: 'KMHRC813ENU169946',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2026-04-03',
            kasko_expiry: '2026-04-03',
            passenger_insurance: 'None'
        },
        {
            id: 60,
            make: 'Hyundai',
            model: 'Venue',
            year: 2022,
            license_plate: 'AB256GF',
            chassis: 'KMHRC813ENU170033',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2026-04-03',
            kasko_expiry: '2026-04-03',
            passenger_insurance: 'None'
        },
        {
            id: 61,
            make: 'Hyundai',
            model: 'Venue',
            year: 2022,
            license_plate: 'AB280GF',
            chassis: 'KMHRC813ENU169860',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2026-04-03',
            kasko_expiry: '2026-04-03',
            passenger_insurance: 'None'
        },
        {
            id: 62,
            make: 'Hyundai',
            model: 'Venue',
            year: 2022,
            license_plate: 'AB284GF',
            chassis: 'KMHRC813ENU170082',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'KUQE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2026-04-03',
            kasko_expiry: '2026-04-03',
            passenger_insurance: 'None'
        },
        {
            id: 63,
            make: 'Hyundai',
            model: 'Venue',
            year: 2022,
            license_plate: 'AB311GF',
            chassis: 'KMHRC813ENU170098',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BLU',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2026-04-03',
            kasko_expiry: '2026-04-03',
            passenger_insurance: 'None'
        },
        {
            id: 64,
            make: 'Hyundai',
            model: 'Kona',
            year: 2022,
            license_plate: 'AB231GH',
            chassis: 'KMHC381GFNU152001',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'DULE HASIMI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2026-04-04',
            kasko_expiry: '2026-04-04',
            passenger_insurance: '2026-04-04'
        },
        {
            id: 65,
            make: 'Hyundai',
            model: 'Santa Fe',
            year: 2022,
            license_plate: 'AB055GM',
            chassis: 'KMHS381HHNU425257',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'FREE FARMA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2026-04-08',
            kasko_expiry: '2026-04-08',
            passenger_insurance: 'None'
        },
        {
            id: 66,
            make: 'Hyundai',
            model: 'Accent',
            year: 2021,
            license_plate: 'AB345FO',
            chassis: 'Z94K241BBNR321306',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-01-21',
            kasko_expiry: '2025-01-21',
            passenger_insurance: 'None'
        },
        {
            id: 67,
            make: 'Hyundai',
            model: 'Kona',
            year: 2022,
            license_plate: 'AB317GU',
            chassis: 'KMHK381GFNU152015',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: '2HH SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-06-07',
            kasko_expiry: '2025-06-07',
            passenger_insurance: '2025-06-07'
        },
        {
            id: 68,
            make: 'Hyundai',
            model: 'Kona',
            year: 2022,
            license_plate: 'AB301GU',
            chassis: 'KMHK381GFNU152012',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: '2HH SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-06-07',
            kasko_expiry: '2025-06-07',
            passenger_insurance: '2025-06-07'
        },
        {
            id: 69,
            make: 'Hyundai',
            model: 'Kona',
            year: 2022,
            license_plate: 'AB889GP',
            chassis: 'KMHK381GFNU152070',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2026-05-29',
            kasko_expiry: '2026-05-28',
            passenger_insurance: '2026-05-29'
        },
        {
            id: 70,
            make: 'Hyundai',
            model: 'Kona',
            year: 2022,
            license_plate: 'AB876GP',
            chassis: 'KMHK381GFNU152067',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2026-05-29',
            kasko_expiry: '2026-05-28',
            passenger_insurance: '2026-05-29'
        },
        {
            id: 71,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB326GZ',
            chassis: 'KMHKM81AFNU076138',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'LULEZIM AHMETAJ PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-06-25',
            kasko_expiry: '2025-06-25',
            passenger_insurance: '2025-06-25'
        },
        {
            id: 72,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB644HD',
            chassis: 'Z94K241BBNR336350',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 73,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB625HD',
            chassis: 'Z94K241BBNR336349',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: 'MAKINA NUK',
            kasko_expiry: 'MAKINA NUK',
            passenger_insurance: 'None'
        },
        {
            id: 74,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB639HD',
            chassis: 'Z94K241BBNR336303',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 75,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB616HD',
            chassis: 'Z94K241BBNR336301',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 76,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB647HD',
            chassis: 'Z94K241BBNR335923',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 77,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB634HD',
            chassis: 'Z94K241BBNR335922',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 78,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB631HD',
            chassis: 'Z94K241BBNR335921',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 79,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB650HD',
            chassis: 'Z94K241BBNR335920',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 80,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB784HD',
            chassis: 'Z94K241BBNR336348',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 81,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB816HD',
            chassis: 'Z94K241BBNR341757',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 82,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB779HD',
            chassis: 'Z94K241BBNR341766',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: 'MAKINA NUK',
            kasko_expiry: 'MAKINA NUK',
            passenger_insurance: 'None'
        },
        {
            id: 83,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB770HD',
            chassis: 'Z94K241BBNR342307',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 84,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB781HD',
            chassis: 'Z94K241BBNR342304',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 85,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB757HD',
            chassis: 'Z94K241BBNR342306',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 86,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB776HD ',
            chassis: 'Z94K241BBNR341758',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 87,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB783HD',
            chassis: 'Z94K241BBNR342308',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: 'MAKINA NUK',
            kasko_expiry: 'MAKINA NUK',
            passenger_insurance: 'None'
        },
        {
            id: 88,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB786HD',
            chassis: 'Z94K241BBNR342305',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 89,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB774HD',
            chassis: 'Z94K241BBNR341767',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 90,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB782HD',
            chassis: 'Z94K241BBNR335924',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 91,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB793HD',
            chassis: 'Z94K241BBNR335916',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AUTO HOLIDAY ALBANIA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 92,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB798HD',
            chassis: 'Z94K241BBNR341759',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 93,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB771HD',
            chassis: 'Z94K241BBNR336299',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 94,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB768HD',
            chassis: 'Z94K241BBNR335918',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 95,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB759HD',
            chassis: 'Z94K241BBNR336300',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 96,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB763HD',
            chassis: 'Z94K241BBNR335917',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 97,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB775HD ',
            chassis: 'Z94K241BBNR335926',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 98,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB773HD',
            chassis: 'Z94K241BBNR335919',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 99,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB794HD',
            chassis: 'Z94K241BBNR335925',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 100,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB745HD',
            chassis: 'Z94K241BBNR336298',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 101,
            make: 'Hyundai',
            model: 'Accent',
            year: 2022,
            license_plate: 'AB740HD',
            chassis: 'Z94K241BBNR336302',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ARJAN KURTI PF',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-05',
            kasko_expiry: '2025-07-05',
            passenger_insurance: 'None'
        },
        {
            id: 102,
            make: 'Ford',
            model: 'Ka + ',
            year: 2018,
            license_plate: 'AA452VX',
            chassis: 'MAJUXXMTKUJR29266',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE RENTALS SHPK  ',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2023-12-26',
            kasko_expiry: '2023-12-26',
            passenger_insurance: 'None'
        },
        {
            id: 103,
            make: 'Ford',
            model: 'Focus ',
            year: 2019,
            license_plate: 'AB913AU',
            chassis: 'WF0MXXGCHMKD09165',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2024-04-27',
            kasko_expiry: '2024-05-01',
            passenger_insurance: 'None'
        },
        {
            id: 104,
            make: 'Hyundai',
            model: 'Ioniq',
            year: 2022,
            license_plate: 'AB617HJ',
            chassis: 'KMHC751JFNU086877',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2024-08-29',
            kasko_expiry: '2024-08-03',
            passenger_insurance: '2024-08-24'
        },
        {
            id: 105,
            make: 'Hyundai',
            model: 'Ioniq',
            year: 2022,
            license_plate: 'AB571HJ',
            chassis: 'KMHC751JFNU086878',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2024-08-03',
            kasko_expiry: '2024-08-03',
            passenger_insurance: '2024-08-24'
        },
        {
            id: 106,
            make: 'Ford',
            model: 'Transit',
            year: 2017,
            license_plate: 'AA524SF',
            chassis: 'WF0FXXTTGFHM05468',
            status: 'Available',
            mileage: 0,
            owner: 'AB INVESTMENTS SHPK',
            color: 'GRI E ERRET',
            client: 'AB INVESTMENTS SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2024-05-15',
            kasko_expiry: '2024-05-18',
            passenger_insurance: 'None'
        },
        {
            id: 107,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AG106T',
            chassis: 'KMHK381GFMU137988',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: '2HH SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-04',
            kasko_expiry: '2025-07-04',
            passenger_insurance: '2025-06-30'
        },
        {
            id: 108,
            make: 'Hyundai',
            model: 'Kona',
            year: 2021,
            license_plate: 'AG107T',
            chassis: 'KMHK381GFMU137981',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'H&H TAXI SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-07-10',
            kasko_expiry: '2025-07-10',
            passenger_insurance: '2025-07-10'
        },
        {
            id: 109,
            make: 'Cadillac',
            model: 'Escalade',
            year: 2015,
            license_plate: 'AB999ES',
            chassis: '1GYS47KJ3FR238256',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE RENTALS SHPK  ',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2024-12-12',
            kasko_expiry: 'nan',
            passenger_insurance: 'None'
        },
        {
            id: 110,
            make: 'Hyundai',
            model: 'Santa Fe',
            year: 2022,
            license_plate: 'AB457HV',
            chassis: 'KMHS3811DNU056096',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'AIDA SPAHI',
            insurance: 'ANSIG',
            tpl_expiry: '2025-10-31',
            kasko_expiry: '2025-10-31',
            passenger_insurance: 'None'
        },
        {
            id: 111,
            make: 'Land Rover',
            model: 'Range Rover Sport',
            year: 2022,
            license_plate: 'AC111LA',
            chassis: 'SALWA2BW2NA246305',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'TAXI LUX SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-14',
            kasko_expiry: '2025-10-14',
            passenger_insurance: 'None'
        },
        {
            id: 112,
            make: 'Volvo',
            model: 'S90',
            year: 2021,
            license_plate: 'AB798DS',
            chassis: 'LVYPSK2VCMP100313',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'ZEZE',
            client: 'HANXHARI GROUP SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-10-15',
            kasko_expiry: '2025-10-22',
            passenger_insurance: 'None'
        },
        {
            id: 113,
            make: 'Hyundai',
            model: 'Santa Fe',
            year: 2022,
            license_plate: 'AC303KD',
            chassis: 'KMHS381HHNU448726',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'DONJET MIRAKA',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-05',
            kasko_expiry: '2025-12-05',
            passenger_insurance: 'None'
        },
        {
            id: 114,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2022,
            license_plate: 'AB303DO',
            chassis: 'KMHKM81CPNU082698',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'JESHILE',
            client: 'FERMA 100 SHPK',
            insurance: 'ATLANTIK',
            tpl_expiry: '2024-05-04',
            kasko_expiry: '2026-03-06',
            passenger_insurance: 'None'
        },
        {
            id: 115,
            make: 'Ford',
            model: 'Ka + ',
            year: 2018,
            license_plate: 'AA215VF ',
            chassis: 'MAJUXXMTKUJJ72341',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'PORTOKALLI E ERRET',
            client: 'ECORENT SARANDA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2024-11-01',
            kasko_expiry: 'nan',
            passenger_insurance: 'None'
        },
        {
            id: 116,
            make: 'Ford',
            model: 'Ka + ',
            year: 2018,
            license_plate: 'AA216VF',
            chassis: 'MAJUXXMTKUJJ72340',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'PORTOKALLI E ERRET',
            client: 'ECORENT SARANDA SHPK',
            insurance: 'SIGMA',
            tpl_expiry: '2024-11-01',
            kasko_expiry: 'nan',
            passenger_insurance: 'None'
        },
        {
            id: 117,
            make: 'Bmw',
            model: '740D Xdrive',
            year: 2022,
            license_plate: 'AC031OP',
            chassis: 'WBA21EJ010CM38894',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'OLGER PRIFTI',
            insurance: 'ALBSIG',
            tpl_expiry: 'nan',
            kasko_expiry: '2025-11-24',
            passenger_insurance: 'None'
        },
        {
            id: 118,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB159MV',
            chassis: 'KMHKN81EFPU225016',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 119,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB182MV',
            chassis: 'KMHKN81EFPU225012',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 120,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB128MV',
            chassis: 'KMHKN81EFPU224983',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 121,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB106MV',
            chassis: 'KMHKN81EFPU224971',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 122,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB167MV',
            chassis: 'KMHKN81EFPU224958',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 123,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB156MV',
            chassis: 'KMHKN81EFPU224650',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 124,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB190MV',
            chassis: 'KMHKN81EFPU224644',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 125,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB135MV',
            chassis: 'KMHKN81EFPU224632',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 126,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB144MV',
            chassis: 'KMHKN81EFPU221561',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 127,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB140MV',
            chassis: 'KMHKN81EFPU221560',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 128,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB139MV',
            chassis: 'KMHKN81EFPU220805',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 129,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB112MV',
            chassis: 'KMHKN81EFPU220802',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 130,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB180MV',
            chassis: 'KMHKN81EFPU224525',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 131,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB136MV',
            chassis: 'KMHKN81EFPU224542',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 132,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB125MV',
            chassis: 'KMHKN81EFPU224557',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 133,
            make: 'Hyundai',
            model: 'Ioniq 5',
            year: 2023,
            license_plate: 'AB152MV',
            chassis: 'KMHKN81EFPU224558',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'TAXI LUX SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-01-21',
            kasko_expiry: '2026-01-21',
            passenger_insurance: '2026-01-21'
        },
        {
            id: 134,
            make: 'Ford',
            model: 'Mondeo',
            year: 2017,
            license_plate: 'AA252RV',
            chassis: 'WF0DXXWPCHHB55636',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: 'nan',
            kasko_expiry: 'nan',
            passenger_insurance: 'None'
        },
        {
            id: 135,
            make: 'Ford',
            model: 'Mondeo',
            year: 2016,
            license_plate: 'AA784PF',
            chassis: 'WF0EXXWPCEGL62902',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: 'nan',
            kasko_expiry: 'nan',
            passenger_insurance: 'None'
        },
        {
            id: 136,
            make: 'Ford',
            model: 'Kuga',
            year: 2019,
            license_plate: 'AA905ZX',
            chassis: 'WF0AXXWPMAKY81755',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: 'nan',
            kasko_expiry: 'nan',
            passenger_insurance: 'None'
        },
        {
            id: 137,
            make: 'Ford',
            model: 'Tourneo',
            year: 2018,
            license_plate: 'AB892EM',
            chassis: 'WF0UXXWPGUJT63874',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'VERDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: 'nan',
            kasko_expiry: 'nan',
            passenger_insurance: 'None'
        },
        {
            id: 138,
            make: 'Ford',
            model: 'Puma ',
            year: 2022,
            license_plate: 'AB186IB',
            chassis: 'WF02XXERK2NM67549',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-18',
            kasko_expiry: '2025-10-18',
            passenger_insurance: 'None'
        },
        {
            id: 139,
            make: 'Ford',
            model: 'Transit',
            year: 2022,
            license_plate: 'AB561IB',
            chassis: 'WF01XXTTG1NB45319',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-10-23',
            kasko_expiry: '2025-10-23',
            passenger_insurance: 'None'
        },
        {
            id: 140,
            make: 'Audi',
            model: 'A6',
            year: 2015,
            license_plate: 'AB176LT',
            chassis: 'WAUZZZ4GXGN020260',
            status: 'Available',
            mileage: 0,
            owner: 'ANTIGONE FINANCIAL ENTERPRISE',
            color: 'BARDHE',
            client: 'ROBERT BAMOVA',
            insurance: 'SIGMA',
            tpl_expiry: 'nan',
            kasko_expiry: '2025-04-10',
            passenger_insurance: 'None'
        },
        {
            id: 141,
            make: 'Mg',
            model: '4',
            year: 2023,
            license_plate: 'AB442NO',
            chassis: 'LSJWH4091PN149859',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'CHICO TAXI SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-03-27',
            kasko_expiry: '2026-03-27',
            passenger_insurance: '2026-04-09'
        },
        {
            id: 142,
            make: 'Mg',
            model: '4',
            year: 2023,
            license_plate: 'AB281OA',
            chassis: 'LSJWH4097PN092602',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ALPHA TAXI ',
            insurance: 'nan',
            tpl_expiry: '2026-04-27',
            kasko_expiry: '2026-04-27',
            passenger_insurance: '2026-04-27'
        },
        {
            id: 143,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB291OL',
            chassis: 'KNADA814BRT953051',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'KUQE',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2025-05-30',
            kasko_expiry: '2025-05-30',
            passenger_insurance: 'None'
        },
        {
            id: 144,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB307OL',
            chassis: 'KNADA814BRT953809',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'KUQE',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2025-05-30',
            kasko_expiry: '2025-05-30',
            passenger_insurance: 'None'
        },
        {
            id: 145,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB306OL',
            chassis: 'KNADA814BRT953810',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'KUQE',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2025-05-30',
            kasko_expiry: '2025-05-30',
            passenger_insurance: 'None'
        },
        {
            id: 146,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB956OR',
            chassis: 'KNADA814BRT961283',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BLU',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2025-06-18',
            kasko_expiry: '2025-06-18',
            passenger_insurance: 'None'
        },
        {
            id: 147,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB237OG',
            chassis: 'KNADA814BRT919389',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2026-05-12',
            kasko_expiry: '2026-05-12',
            passenger_insurance: 'None'
        },
        {
            id: 148,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB167OG ',
            chassis: 'KNADA814BRT935734',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BLU',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2026-05-12',
            kasko_expiry: '2026-05-12',
            passenger_insurance: 'None'
        },
        {
            id: 149,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB217OG',
            chassis: 'KNADA818ART945956',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'KUQE',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2026-05-12',
            kasko_expiry: '2026-05-12',
            passenger_insurance: 'None'
        },
        {
            id: 150,
            make: 'Kia',
            model: 'Stonic',
            year: 2023,
            license_plate: 'AB246OG',
            chassis: 'KNADA818ART945985',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'KUQE',
            client: 'AZAL',
            insurance: 'SIGMA',
            tpl_expiry: '2026-05-12',
            kasko_expiry: '2026-05-12',
            passenger_insurance: 'None'
        },
        {
            id: 151,
            make: 'Mercedes Benz',
            model: 'E Class',
            year: 2018,
            license_plate: 'AB414LC',
            chassis: 'WDD2130131A455163',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'BODINI TRAVEL',
            insurance: 'SIGMA',
            tpl_expiry: 'nan',
            kasko_expiry: '2026-05-29',
            passenger_insurance: 'None'
        },
        {
            id: 152,
            make: 'Bmw',
            model: '750',
            year: 2018,
            license_plate: 'AB970OK',
            chassis: 'WBA7F2C52JG424804',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'BODINI TRAVEL',
            insurance: 'SIGMA',
            tpl_expiry: 'nan',
            kasko_expiry: '2025-06-02',
            passenger_insurance: 'None'
        },
        {
            id: 153,
            make: 'Land Rover',
            model: 'Discovery',
            year: 2023,
            license_plate: 'AB181OG',
            chassis: 'SALRA2BW1P2484687',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2026-05-12',
            kasko_expiry: '2026-05-12',
            passenger_insurance: 'None'
        },
        {
            id: 154,
            make: 'Hyundai',
            model: 'Santa Fe',
            year: 2023,
            license_plate: 'AB854LC',
            chassis: 'KMHS6812DPU077642',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'ZEZE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-11-29',
            kasko_expiry: '2026-05-15',
            passenger_insurance: 'None'
        },
        {
            id: 155,
            make: 'Ford',
            model: 'Kuga',
            year: 2023,
            license_plate: 'AB130PN',
            chassis: 'WF0FXXWPMFRB58008',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BLU',
            client: 'MUSA MEMOCI',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-08-06',
            kasko_expiry: '2025-08-06',
            passenger_insurance: 'None'
        },
        {
            id: 156,
            make: 'Honda',
            model: 'Enp2',
            year: 2024,
            license_plate: 'AB441RZ',
            chassis: 'LHGRM8822S8002231',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI E HAPUR',
            client: 'SAREN INVEST',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-11',
            passenger_insurance: 'None'
        },
        {
            id: 157,
            make: 'Volkswagen',
            model: 'Id3',
            year: 2024,
            license_plate: 'AB469RZ',
            chassis: 'LSVFD6E95R2055759',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'SAREN INVEST',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-11',
            passenger_insurance: 'None'
        },
        {
            id: 158,
            make: 'Volkswagen',
            model: 'Id3',
            year: 2024,
            license_plate: 'AB474RZ',
            chassis: 'LSVFD6E97R2055679',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'SAREN INVEST',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-11',
            passenger_insurance: 'None'
        },
        {
            id: 159,
            make: 'Ford',
            model: 'Transit',
            year: 2020,
            license_plate: 'AB279AY',
            chassis: 'WF01XXTTG1LC50528',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'ANTIGONE RENTALS SHPK  ',
            insurance: 'SIGMA',
            tpl_expiry: '2025-12-17',
            kasko_expiry: '2025-12-17',
            passenger_insurance: 'None'
        },
        {
            id: 160,
            make: 'Ford',
            model: 'Kuga',
            year: 2024,
            license_plate: 'AB614RZ',
            chassis: 'WF0FXXWPMFRL55352',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'GRI',
            client: 'FLORENT PRIFTI',
            insurance: 'ALBSIG',
            tpl_expiry: '2025-12-12',
            kasko_expiry: '2025-12-12',
            passenger_insurance: 'None'
        },
        {
            id: 161,
            make: 'Volkswagen',
            model: 'Id6 ',
            year: 2024,
            license_plate: 'AB117SS',
            chassis: 'LFVVB9E77R5163182',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'KAFE E HAPUR',
            client: 'SHEFQET AHMATI',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-02-06',
            kasko_expiry: '2026-02-06',
            passenger_insurance: 'None'
        },
        {
            id: 162,
            make: 'Byd',
            model: 'Byd7001Beva1',
            year: 2024,
            license_plate: 'AB890TK',
            chassis: 'LGXCE4CC8R0532012',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'FREE FARMA SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-04-09',
            kasko_expiry: '2026-04-09',
            passenger_insurance: 'None'
        },
        {
            id: 163,
            make: 'Byd',
            model: 'Byd7001Beva1',
            year: 2024,
            license_plate: 'AB883TK',
            chassis: 'LGXCE4CC6R0553912',
            status: 'Available',
            mileage: 0,
            owner: 'OTP BANK',
            color: 'BARDHE',
            client: 'FREE FARMA SHPK',
            insurance: 'ALBSIG',
            tpl_expiry: '2026-04-09',
            kasko_expiry: '2026-04-09',
            passenger_insurance: 'None'
        },
    ],
    users: [
        { id: 1, name: 'John Doe' },
        { id: 2, name: 'Jane Smith' },
    ],
    invoices: [
        { id: 1, date: '2023-06-01', customer_id: 1, total: 100 },
        { id: 2, date: '2023-06-15', customer_id: 2, total: 200 },
    ],
};